### PR TITLE
Get sf iter

### PR DESCRIPTION
**Pull request by masmansouri**
Hello and good day,
This pull request adds two new keys to `get_snmw2sf` function, as follows:

1- `limited_nbnd`: which considers a limited number (`nbnd`, now 70%) of virtual states to solve linear equation W_c= (1-vX0)^-1 vX0v and for the rest just applies vX0v and skips the lgmres.

2- `pass_dupl`: finds state whose eigenenergy in mean-field has a small difference with the former one. For such orbitals (m), when the key is True, `sf_aux` will be copied from the last solution. 

3- m_restart has been modified to copy more data (GW_coeff, QP_energy and so forth) with different keys and store in RESTART.HDF5.
4- Some small correction has done in prints.
5- `m_qp_spectra.py` plots the quasi-particle energies as spectra by means of broadening.

All changes will be used if the key is True. therefore there is no impact on the `gw_iter` and already all `nao/test` are passed successfully. The G0W0 correction by applying these keys and use_initial_guess leads to a slight difference in energies and considerable reduction in time. You can find the benchmark for CH3CH2O and Computational time is as follows:

only `initguess`: Total time for kernel# 35376.100615726784
`initguess` + `limited_nbnd` + `pass_dupl` : Total time for kernel# 29699.531461402774
Figure_1

### CODE REVIEW

**Comment by kovalp** [comment]
only initguess: Total time for kernel# 35376.100615726784
initguess + limited_nbnd + pass_dupl : Total time for kernel#
29699.531461402774

So, only a fraction of walltime is saved? 30000 instead of 35000, right?

**Comment by masmansouri** [comment]
It is true. Note that the benchmark molecule is small-sizaed with around 340 virtual states when only for 30% of those orbital the lgmres is skipped. Moreover duplicate energies are mostly in occupied states.

**Comment by mbarbry** [comment]
Hi,

Some nice improvements, curious to see if the gain is higher for larger systems. Did you start some benchmarks?

Otherwise, the changes look good to me. Feel free to merge the branch.

**Comment by kovalp** [comment]
I think it is ok.

However, these changes look as a patchwork to me. These are necessary
experiments, but this is far from production imho. Let's try to get rid of
small matrix elements of W_c in a more general, semi-empirical and tunable
manner.

**Comment by masmansouri** [comment]
Hi,
I submitted jobs for Porphyrin to see what will happen and I will provide you with an update upon completion.
regarding `pass_dupl`, for MF's orbital whose eigenenergy differentiates less than 1e-06(too small?) with former,  sf_aux will be copied from sf_aux [n,m-1,:]. Maybe, we can go further and do this for n, so that for such states `sf_aux [n,:,:]=sf_aux [n-1,:,:]`. I am going to benchmark to what extent it impacts on accuracy and computational time.

**Pull request merged**
