### PR TITLE
small fix in test

### PR DESCRIPTION
**Pull request by mbarbry**
Hi @masmansouri ,

I did not find much issues, only a index isuues for `dp_sparse` tests. Could you confirm it?

### CODE REVIEW

**Comment by masmansouri** [comment]
I received such n error, using latest nao2 version

gw_xvx algo:  ac_sparse
Traceback (most recent call last):
  File "m_gw_xvx.py", line 261, in <module>
    ac_sparse = gw.gw_xvx(algo='ac_sparse')
  File "/home/masoud/software/pyscf/pyscf/nao/gw_iter.py", line 144, in gw_xvx
    xvx = gw_xvx_ac_sparse(self)
  File "/home/masoud/software/pyscf/pyscf/nao/m_gw_xvx.py", line 107, in gw_xvx_ac_sparse
    self.v_pab = self.pb.get_ac_vertex_array(matformat="sparse", dtype=self.dtype)
  File "/home/masoud/software/pyscf/pyscf/nao/prod_basis.py", line 663, in get_ac_vertex_array
    pab2v = self.get_ac_vertex_array_sparse_coo(dtype=dtype)
  File "/home/masoud/software/pyscf/pyscf/nao/prod_basis.py", line 714, in get_ac_vertex_array_sparse_coo
    import sparse
ModuleNotFoundError: No module named 'sparse'

**Comment by mbarbry** [comment]
I think the error message is pretty clear. To be able to use the `ac_sparse` method, you need to install the sparse package.
https://sparse.pydata.org/en/latest/

I will add an error message indicating the dependency.
Anyway, with `ac_sparse` I was just trying things. The method is very inefficient. For large system one should use the `dp_sparse` format.

**Comment by mbarbry** [comment]
I think this issue is solved. If you don't have furhter comments I will merge these small corrections.

**Comment by masmansouri** [comment]
So clearly it is different with Scipy.saprse. I already have Anaconda full version and it means that one needs to install extra packages. is not it possible to stick to global scipy?

**Comment by mbarbry** [comment]
No, the point is to use multidimensional sparse matrices with the `ac_sparce` method, the sparse library handles this, in contrary to the scipy.sparse library which handles only 2D matrices.

Another advantage of the `dp_sparse` method is that it sticks to 2D matrices, therefore no extra dependencies.

**Comment by mbarbry** [comment]
Considering the number of dependencies for this code, I don't think a supplementary python package is an issue.

**Comment by masmansouri** [comment]
Regarding simulation that you had asked, the submitted job has been killed for the following error

- Overwritten attributes  get_jk get_ovlp get_j get_hcore energy_nuc  of <class 'pyscf.scf.hf.SCF'>
- Traceback (most recent call last):
-   File "run_gw_iter.py", line 15, in <module>
-     gw.kernel_gw_iter()
-   File "/scratch/masoud/software/pyscf_ref/pyscf/nao/gw_iter.py", line 623, in make_mo_g0w0_iter
-     self.xvx = self.gw_xvx(self.gw_xvx_algo)
-   File "/scratch/masoud/software/pyscf_ref/pyscf/nao/gw_iter.py", line 162, in gw_xvx
-     xvx = gw_xvx_dp_sparse(self)
-   File "/scratch/masoud/software/pyscf_ref/pyscf/nao/m_gw_xvx.py", line 196, in gw_xvx_dp_sparse
-     return gw_xvx_sparse_dp(self)
-   File "/scratch/masoud/software/pyscf_ref/pyscf/nao/m_gw_xvx_dp_sparse.py", line 14, in gw_xvx_sparse_dp
-     v_pd = self.v_dab.reshape(self.v_dab_csr.shape[0]*self.norbs, self.norbs).tocsr()
-   File "/scratch/scicomp/CentOS/7.3.1611/Haswell/software/Anaconda3/5.3.1/lib/python3.7/site-packages/scipy/sparse/coo.py", line 224, in reshape
-     shape=shape, copy=False)
-   File "/scratch/scicomp/CentOS/7.3.1611/Haswell/software/Anaconda3/5.3.1/lib/python3.7/site-packages/scipy/sparse/coo.py", line 192, in __init__
-     self._check()
-   File "/scratch/scicomp/CentOS/7.3.1611/Haswell/software/Anaconda3/5.3.1/lib/python3.7/site-packages/scipy/sparse/coo.py", line 276, in _check
-     raise ValueError('negative row index found')
- ValueError: negative row index found

**Comment by mbarbry** [comment]
Interesting to see that using a different version of scipy gives an error. Anaconda 5.3 is almost two years old. Things change a lot in scipy, I guess the issue comes from there. But still, to get negative indices, this is odd ...

Could you give me the scipy version installed with this anaconda version. And could you try to use a  the latest version of Anaconda, see if the error repeat.

**Comment by masmansouri** [comment]
scipy and anaconda versions are

module load Anaconda3/5.3.1
$ python3.7
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.1.0'

I will try with
module load Anaconda3/2019.10
$ python3.7
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.3.1'

**Pull request merged**
