### PR TITLE
Improve div eigenenergy gpu

### PR DESCRIPTION
**Pull request by mbarbry**
The div_eigenenergy routine was not optimized for GPU

### CODE REVIEW

**Comment by masmansouri** [comment]
Hi @marc
I just updated my repo and received this error:

~/software/pyscf/pyscf/nao/m_div_eigenenergy_numba.py in <module>
     56 
     57 @cuda.jit(nb.void(nb.float32[:], nb.float32[:], nb.int32, nb.int32, nb.float64, nb.float64,\
---> 58            nb.float32[:, :], nb.float32[:, :]))
     59 def div_eigenenergy_gpu_float32(n2e, n2f, nfermi, vstart, omega_real, omega_imag, nm2v_re, nm2v_im):
     60     """
CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library.

I have not Nvidia hardware on my laptop, so I won't be able use Cuda. Did you add proper conditions to use Cuda, Cupy, and numba.cuda?

**Comment by masmansouri** [comment]
Hi @mbarbry 
I just commented the use of numba in `chi0_matvec.py`. Can you please take a look at `m_div_eigenenergy_numba.div_eigenenergy_numba` function?

**Comment by mbarbry** [comment]
Hi @masmansouri ,

Thanks for letting me know. It is funny that I did not get this error, I tried also on a system without GPU. I will find a fix.

**Comment by mbarbry** [comment]
Improvements impacts on an alpha-NPD molecule (78 atoms, 757 orbitals).
[geo.zip](https://github.com/cfm-mpc/pyscf/files/4569665/geo.zip)


memory_profile

    timing:
    CPU lgmres: 107988.81 s
    GPU v1 lgmres: 92744.89 s
    GPU v2 lgmres: 75231.83 s
    GPU v2 bicgstab: 70100.86

We can see that `bicgstab` solver offers better performances than `lgmres`. The total numbers of iterations performed are

    lgmres: 1173581
    bicgstab: 1043783

Therefore a reduction of 12%

**Comment by masmansouri** [comment]
Great, I wonder how one can find the best solver for a system? Do you think a benchmark of solvers on a set of small systems can give a clear and global answer?

**Comment by kovalp** [comment]
Good idea.

**Comment by mbarbry** [comment]
That would be effectively a good idea. It is now easy to change iterative solver as you may have seen. However, one should also analyze the impact of the solvers options on convergence, which can be cumbersome.

**Comment by masmansouri** [comment]
OK, I'll do it. one clarification, How did you count the number of iterations?

**Comment by masmansouri** [comment]
I had added this object `lgmres_time_per_step` to collect time consumption in lgmres. Should I benchmark solvers vs. spent time or vs. the number of iterations?

**Comment by mbarbry** [comment]
I just count the number of time that the method `chi0_mv` is called. In fact, it will be greater than the number of iterations required by the solver, because we call the method in other places. But most of the call will be made by the iterative solver.

The number of iteration (or call to `chi0_mv`) is saved in the file `gw_iter_chi0_mv.txt`.
I think it makes more sense to compare the number of iterations, the time spent is more tricky to analyze, particularly that the CPU may be solicited by other processes. While the number of iteration will just depend on your solver, and the system you are running (via the loop over `norbs`).

**Comment by masmansouri** [comment]
Fair enough!

**Comment by masmansouri** [comment]
Dear Peter and Marc, 
Following our last conversation, I benchmarked krylov solvers for a set of small systems. I started with solvers that do not need more than available arguments (`A, x, x0, tol, atol, and M`). Among all, `minres` did not converge at all. `cgs` converged too slow so that still several systems are running. Eventually, `bicgstab`, `lgmres`, and `gcrotmk` solvers provide the best performance in terms of the number of chi_0 call, respectively. Please see the figures below. Line graphs w.r.t to spent time in solver also show the same trend.
chi0
time

**Comment by kovalp** [comment]
cool. Bigstab is winner...

**Comment by mbarbry** [comment]
That a nice comparison! Thanks for doing this.
We should include it in a documentation.

Marc

**Pull request merged**
