### PR TITLE
divides convergence in QP into int and res parts

### PR DESCRIPTION
**Pull request by masmansouri**
Hi @kovalp @marc,
Hope you are doing well. This request includes 3 changes:
1- as you know within the QP correction `g0w0_eigvals_iter`, both integral `gw_corr_int_iter(sn2w)` and residues `gw_corr_res_iter(sn2w)` will be iterated to achieve convergence. I found often one of them converges sooner and therefore should not send in the next iteration. e.g in Anthracene this leads to saving 5% of total runtime when residue part converged 3 iterations sooner.
2- adds initial guess to `gw_corr_res_iter` function. Despite it is led to worse timing in Anthracene, I am trying with a larger system!
3- improves the reports and prints by adding better timing for the main algos in GW classes.

### CODE REVIEW

**Comment by mbarbry** [comment]
Hi @masmansouri ,

Looks good to me. I'm curious to see how the QP correction impact performances overall.
Also a small comment on the convergence of iterative algorithms like gmres. If the convergence is difficult and you don't know a good initial guess, what could strongly help is preconditioning.

if you consider your linear system of equation

    Ax = b

The idea consists of finding an approximation to the inverse of matrix A which is easy to calculate, typically you could take the diagonal element. Then your system of equations can write

    M**(-1) Ax = M**(-1)b

where M is your preconditioner. You have many resources on this in the internet (for example https://www-users.cs.umn.edu/~saad/Calais/PREC.pdf). Preconditioning can dramatically improve convergence.

In SciPy solvers, the argument for the preconditioning is named `M`, see
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lgmres.html

**Comment by masmansouri** [comment]
@mbarbry , Thanks for the comment.
in def `snm2wsf`, A in Ax = b is a LinearOperator `k_c_opt`. But as far as I read, precoditioner(M) usually is efficient for cases that A is a sparse square matrix and then M can be calculated as follows 
```
import scipy.sparse.linalg as spla
M_x = lambda x: spla.spsolve(A, x)
M = spla.LinearOperator((n, n), M_x)
```
Please let me know if I am mistaken!

**Comment by mbarbry** [comment]
Hi @masmansouri ,

In the ideal case, `A` is a matrix and `M` as well. However, often as you probably know, you do not know the exact form of the matrix `A` or it is too expensive to calculate. The power of iterative methods such as `gmres` is in the fact that you just need to know an approximation to the matrix vector product `Ax`. It is why in the NAO code, we are using linear operators. But even without knowing the exact form of the matrix A, you can always get an approximation for the preconditioner. In order to find it, you need to look at the mathematical expression of the matrix vector product.

The example you mentioned from scipy documentation is basic. But preconditioning is a much more broad method. In the paper below, in section 3, they give some examples of preconditioning for a particular methods called Jacobian-free Newton-Krylov used to solve non-linear system of equations. It may help you understanding how preconditioning works.

[1-s2.0-S0021999103004340-main.pdf](https://github.com/cfm-mpc/pyscf/files/4513957/1-s2.0-S0021999103004340-main.pdf)

**Comment by masmansouri** [comment]
Hi @mbarbry,
How do u see this preconditioner? For Anthracene, it has decreased the spent time in lgmrs loop around 5%. 

    def precond_lgmres (self, omega=None):
    omega = 1j*10.0 if omega is None else omega
    v = np.ones(self.nprod, dtype=self.dtypeComplex)                           
    vX = self.chi0_mv (v, comega=omega)
    
    vX2 = 1 - vX
    l = np.zeros((self.nprod,self.nprod), dtype=self.dtypeComplex) 
    np.fill_diagonal(l, vX2)

    #from numpy.linalg import pinv
    #M=pinv(l)
    l = csc_matrix (l)
    M_x = lambda x: spla.spsolve(l, x) 
    M = spla.LinearOperator((self.nprod, self.nprod), M_x)
    return M

I am gonna merge this pull if it is fine with you.

**Comment by mbarbry** [comment]
Hi @masmansouri ,

5% of time improvement is not much. I think it would be more meaningful to analyze the impact of the preconditioning using the number of iterations instead of timing (could be nice also to see what are the norms of the residue with and without preconditioning).

For the form of the preconditioner itself, I do not have the full mathematic picture in mind, so it is difficult for me to judge. The equation you are solving with the iterative method is equation 34 in the GW paper of Peter, correct?

**Comment by masmansouri** [comment]
Hi @mbarbry 
That is true. eq (34) 
k_c_opt provides linear operator mimics (1 - v * chi_0) as A in Ax=b and preconditioner (M) approximates A*-1 using a simple potential np.one array.

**Pull request merged**
