### PR TITLE
Matmat sparse dense

### PR DESCRIPTION
**Pull request by mbarbry**
in `sm0_sum` algo in `kmat_den`, the conversion to sparse matrix in the following line becomes prohibitive for large systems. 

    a_bp2vd = sparse.coo_matrix(a_ap2v.dot(dm), dtype=a_ap2v.dtype).tocsr()

The solution is to use a sparse matrix dense matrix multiplication with return directly a sparse matrix in CSR format.

### CODE REVIEW

**Comment by kovalp** [comment]
I will have to remember where it is

**Comment by mbarbry** [comment]
@kovalp and @masmansouri ,

I think these improvements are ready, in summary, I added

* a sparse matrix dense matrix multiplication which returns a sparse matrix in CSR format (avoid dense to sparse conversion in `m_kmat_den` which was taking most of the time for large systems).
* I cleaned up the `sm0_sum` alogo in `m_kmat_den`
* I added a new input parameter `SCF_kernel_conv_tol` to be able to change the tolerance for the SCF iterations, it was fixed to `1.0e-9` by default, which was too hard to reach for large systems.

Tests are passing, let me know if you have some comments.

**Comment by kovalp** [comment]
Kmat? Is it Fock matrix?

**Comment by mbarbry** [comment]
It looks like, in the comments of the function I can read

    Computes the matrix elements of Fock exchange operator

Is it an issue?

**Comment by kovalp** [comment]
Sorry, I forgot.

**Pull request merged**
