### PR TITLE
Restart fix

### PR DESCRIPTION
**Pull request by mbarbry**
Hi @masmansouri ,

Trying to run gw_iter, I encounter some issues with the `read_rst_h5py` functions.
Therefore I did a few changes, do you have any comments?

Also, I could not find the function `find` in the code, where is it defined?

Best,
Marc

### CODE REVIEW

**Comment by masmansouri** [comment]
Hi Marc, 
Could you comment on what kind of problem you encountered?
In `m_restart.py` I defined different methods to store and parse W_c including `yaml`. 'find' is also in m_restart at the end.  Despite, enclosed you can find `m_restart.py`, just remove txt extension. 
[m_restart.py.txt](https://github.com/cfm-mpc/pyscf/files/3946510/m_restart.py.txt)

.

**Comment by mbarbry** [comment]
I was trying to run `gw_iter` with `restart_w=True`, as I understood, this permit to save quite a lot of computation time by avoiding to recalculate W_c. However, the first time you run the calculation, the file `SCREENED_COULOMB.hdf5` does not exist, and thus the code was failing.

My idea here is just to enforce the calculation of Wc if the file can not be loaded.

In the nao2 branch, the function find is not defined.

So there is an option to use yaml instead of hdf5 to store the W_c? How large is the matrix? Since yaml is text based, hdf5 will be more appropriate to store large amounts of data.

**Comment by masmansouri** [comment]
That is true that storing W_c is more economic in terms of computational cost and this is also true that for the first calculation there is no stored file to be read :-).  I think it is now coded in `gw_iter.py` where
`    if (self.write_w==True):
        from pyscf.nao.m_restart import write_rst_h5py
        print(write_rst_h5py(data = snm2i, filename= 'SCREENED_COULOMB.hdf5'))`

About the size, I agree with you that `hdf5` is more efficient. however, the generic full matrix elements of W_c usually is not too large. because we calculate it usually only for several orbitals above and below fermi. therefore, it is typically less than 10 MB and for such a file size `yaml` also works well.
But if one wants to calculate GW for all states, `hdf5` will show its superiority. Once I dealt with a matrix about 2 GB. The default is `hdf5`.

**Comment by mbarbry** [comment]
Hi @masmansouri ,

Are you ok with these changes?
I think they are necessary, therefore I would like to merge them into `nao2` branch

**Pull request merged**
