### PR TITLE
Speed up gw iter2

### PR DESCRIPTION
**Pull request by mbarbry**
These changes should give substantial speed up, I managed to run C60 in 60 hours instead of 110 hours. It still need to be confirmed with this branch.

Also, it could give speed up to compile with Release flag

    cmake -DCMAKE_BUILD_TYPE=Release ..

The main point is to use `np.dot` instead of scipy `blas.gemm`, probably an issue with array ordering since both functions should be calling mkl `GEMM` underneath ...

If `blas.gemm` is called with C ordered arrays, the performance are degradated. Probably `np.dot` automatically does the conversion, not sure.

### CODE REVIEW

**Comment by kovalp** [comment]
Cool

**Comment by mbarbry** [comment]
C60 timing is 57 hours (2.06e5 s)

chi0_mv: 51%
CSR_matvec: 34% total time
np.dot: 37%

**Comment by kovalp** [comment]
Let me return to one important question. The 51% percentage of time is it
out of total time or out of correlation part (i.e. excluding initial HF)?

**Comment by mbarbry** [comment]
It is the total runtime.

The initial HF takes 10% of total runtime

**Comment by kovalp** [comment]
Could you try the same calculation with mbpt_lcao? I have my doubts now
about the iterative algorithm in GW...

Maybe you correct too many states in GW?

**Comment by mbarbry** [comment]
I will give it a try, but it will take me some time to do a proper comparison.

It is possible that the input parameters are not optimal. What parameter controls the correction fo the states in GW?

**Comment by kovalp** [comment]
>What parameter controls the correction fo the states in GW?

There are some arguments in the initializers like nocc, nvirt. If they are
not set, then they must be 10 and 10 (Right, Masoud?) which is optimal.

**Comment by masmansouri** [comment]
The default number of states, i.e. self.nn, to be corrected is 6 for occupied and 6 for virtual states. As Peter said with nocc and nvirt, one can control those parameters.

**Comment by kovalp** [comment]
Another idea. Maybe the precision of the solver is excessively high? In
tddft we were satisfied with something like atol=1e-3, right? Is this
parameter controlled in gw_iter? How is it choosen?

**Comment by masmansouri** [comment]
I think it is set to 1e-04 for both classes. However, it might be too stringent in gw_iter  especially for molecules whose W is typically weak.

**Comment by mbarbry** [comment]
I used 1.0e-4 for these calculations.

The lgmres solver needs around 7 iterations to converge, which is relatively fast. However, we could probably reduce this number to 3 or 4 if we would use a preconditioner.
I have played quite a bite with Krylov iterative methods these past years, and already just providing an approximation to the diagonal of the inverse matrix can help quite a bit.

Do you think it would be difficult to get a preconditioner for this equation?

We could also try other solvers which can be faster for this specific problem.

**Comment by kovalp** [comment]
I see. It is under good control. 7 iterations looks small to me.

Next parameter is the number of frequencies. How big was it?

**Comment by mbarbry** [comment]
I'm using the default value which is 32 frequencies.

I just tried the bicgstab instead of lgmres and it permits to reduce the number of iteration from 6 to 4 for CH4.

**Comment by kovalp** [comment]
How many linear equations do we solve for C60?

**Comment by mbarbry** [comment]
For C60, chi0_mv is called 69007 times per frequencies.

knowing that the first loop 

    for n in range(len(self.nn[s])):

has a size of 12, and the second loop

    for m in range(self.norbs):

has a size of 780

**Comment by mbarbry** [comment]
Another thing that could be done to reduce number of iterations would be to use an initial guess, maybe from previous frequencies?

**Comment by kovalp** [comment]
67000 is the total? Or 32*67000 is the total number of chi0 times vector?

**Comment by mbarbry** [comment]
32*67000 is the total, which is quite a lot!

but it is `nfreq*len(self.nn[s])*self.norbs*nite_lgmres`, i.e, `32*12*780*nite_lgmres`,

Therefore if `nite_lgmres ~ 7` we get a total of 2096640 calls of `chi0_mv` for C60 ....

**Comment by kovalp** [comment]
The loop over the norbs can be spared to a large extend (I think 5 times
less dimension) if we transform this sum (later in the algorithm this
dimension is summed over) into an approximate numerical integration.

There is already some experiments about this in the code.

**Comment by kovalp** [comment]
This is equivalent to a very high resolved tddft calculation...

**Comment by mbarbry** [comment]
This would be quite an improvement. Do you remember where in the code it was tried?

**Pull request merged**
