### PR TITLE
Gw iter gpu

### PR DESCRIPTION
**Pull request by mbarbry**
GPU version running, but the results are off.

It seems there is some issues with the matrix-matrix operations ...

### CODE REVIEW

**Comment by kovalp** [comment]
Is it working now?

**Comment by mbarbry** [comment]
The GPU version is running, but the results are off, almost 1 eV in the band gap for CH4 molecule.
I investigated a bit, and it seems that there are some issues with GEMM operation on GPU. I have to dig deeper.

I also corrected a bug with float32 CSR matvec, we can now use float arrays with gw_iter, which was not supported. It is why I merged the branch even if GPU results are off.

I also found that it is faster to use column major for Blas operations. for GEMM, it provide a gain up to 50%! I will implement this in a new branch.


[test.py.zip](https://github.com/cfm-mpc/pyscf/files/4017131/test.py.zip)

**Comment by kovalp** [comment]
I see.

I read that composition is a preferable software design pattern than
inheritance. I wish you prefered the composition in the newly written code.

Column major? Can you express it in a blas call? Is it perhaps because the
opposite solution row major (?) needs transposes?

I believe in Gw we use double ptecision numbers. Could you use single
precision? How does it affect results?

1 eV is a large discrepancy. Something must be wrongly written. There is a
slogan, you know: "if it does not work, it does matter how fast it doesn't
work" :-)

**Comment by mbarbry** [comment]
I think the speed up for the BLAS routines is just caused by the fact that BLAS is written in Fortran, and is probably optimized for column major arrays.

The differences between single and double precision is small (~1.0e-6 for the band gap of CH4), an error acceptable I believe.

I agree that 1.0eV is large. I have to find out where the problem is. But it will take a bit of time. I have to remember how GPU computing is working ... In the meantime, I added a warning when using GPU.

**Comment by kovalp** [comment]
The differences between single and double precision is small (~1.0e-6 for
the band gap of CH4), an error acceptable I believe.

It would be great to use single precision in screened interaction. I
believe it is 10-15 times faster than double precision!

**Pull request merged**
