### PR TITLE
rf0_den - no numba by default

### PR DESCRIPTION
**Pull request by mbarbry**
@kovalp @masmansouri 

Do you agree with this fix? Would have been nicer to solve it, but not the priority at the moment.

Do not use numba for rf0_den by default. Numba raise some warning in some tests

    m_rf0_den.py:122: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 2d, A), array(float64, 2d, C)) np.dot(k_c.imag, kernel_sq)

### CODE REVIEW

**Comment by kovalp** [comment]
I agree in principle, but I cannot review the source now.

**Comment by masmansouri** [comment]
It is OK as long as it does not cause extra failed errors ;0)

**Comment by kovalp** [comment]
But, were you able to check this?

**Comment by mbarbry** [comment]
I checked with some tests it was ok, I'm now running all the tests before to merge.

**Comment by masmansouri** [comment]
I already have installed it on my laptop

**Comment by mbarbry** [comment]
ok all the tests are passing excepted the one that are known to fails.
I will merge

**Pull request merged**
