### PR TITLE
Continue improvements

### PR DESCRIPTION
**Pull request by mbarbry**
* dynamic parallelization of CSR matvec
* parallelel div_eigenenergy
* initial guess for iterative solver

### CODE REVIEW

**Comment by mbarbry** [comment]
Dear @masmansouri  and @kovalp 

Here are some further improvements for gw_iter.

The main improvement is the option to use initial guess for the iterative solver. This allows running calculations for C60 in 38 hours (instead of 58 hours). However, since the solutions of the iterative solver are slightly different, the obtained energies are slightly modified.

If decreasing `gw_iter_tol`, the results with and without initial guess should converge, but I still have to check this point. Let me know what you think.

**Comment by kovalp** [comment]
I think this is great!

**Comment by mbarbry** [comment]
I can confirm that when decreasing `gw_iter_tol` to 1.0e-8, both methods converge toward the same solution. All the tests are passing, therefore, if you do not have further comments I will merge the pull request.

**Comment by kovalp** [comment]
I am positive.

How do you construct the guess?

**Comment by mbarbry** [comment]
The initial guess `x0` is obtained from previous frequencies

    x0 = sf_aux[iw-1, n, m, :]

In fact, I'm suspecting that `sf_aux` is identical for the first 20 frequencies (for a total of 32 frequencies) because the iterative solver calls the matvec operation only one time for `iw = 1` to `~20`, and then the number of call of `chi0_mv` slightly increases for the remaining frequencies points.

If it is true, it could strongly reduce the computational cost, however, I would be quite odd. I will check it.

**Comment by kovalp** [comment]
That is very funny what you say. First 20 freq out of 32 possess the same
matrix elements.

You could easily plot the matrix-elements along m, i.e. for a given w, n,
and mu. The index m can be also easily substituted with the HF eigenenergy
E_m. This will be almost what we need according to my last-week's proposal.

Peter

**Comment by kovalp** [comment]
A closer function would be this solution multiplied with xvx still for a
given n and m and with contracted (summed over) mu.

**Comment by mbarbry** [comment]
it is something to definitively look at!

**Pull request merged**
