### PR TITLE
Gw chi0 mv improvements

### PR DESCRIPTION
**Pull request by mbarbry**
CSC matvec are very slow in `chi0_mv`, replace them with CSR matvec.

### CODE REVIEW

**Comment by kovalp** [comment]
Really? How much faster? I dont recall if there are csc I thought every
matrix was csr... Comments?

**Comment by mbarbry** [comment]
I did tests on a small molecule, C4H7NO4, it gave a speed up of almost two overall. I'm now trying on a larger molecule.

The CSC matrices appear at the steps 2, 4, 14 and 16, i.e.,

    sab_real = (vdp*self.v_dab).reshape((self.norbs,self.norbs)
    sab_imag = (vdp*self.v_dab).reshape((self.norbs, self.norbs))

    chi0_re = vdp*self.cc_da
    chi0_im = vdp*self.cc_da

The matrices involved in the lines above are in CSR format, however, the lines above are equivalent to

    sab_real = self.v_dab.T.dot(vdp).reshape((self.norbs,self.norbs)
    sab_imag = self.v_dab.T.dot(vdp).reshape((self.norbs, self.norbs))

    chi0_re = self.cc_da.T.dot(vdp)
    chi0_im = self.cc_da.T.dot(vdp)

And the transpose of a CSR matrix is a CSC matrix, thus the matrix-vectors products use the CSC version.

The solution was is to precalculate the transpose of the matrices `v_dab ` and `cc_da` in CSC format (and thus get  CSR matrices). Then we can use the `csr_matvec` routine from `sparse_tools` which is parralelized and much faster than the scipy CSC matvec (and also avoid the constant conversion of the CSR matrices to the CSC format).

**Comment by kovalp** [comment]
That's what we need now! Thank you!

**Comment by mbarbry** [comment]
Glad to hear that it helps.

What are your plans for the GW code? if I can ask.

**Comment by mbarbry** [comment]
Tests are broken

**Pull request closed without merging**
