### PR TITLE
split cuda reoutines in a new module

### PR DESCRIPTION
**Pull request by mbarbry**
Hi @masmansouri ,

This should fix the issue with Cuda. Sorry for the problem, it seems I forgot to tests these last improvements on a machine without GPU.

Let me know if you encounter further issues.

### CODE REVIEW

**Comment by kovalp** [comment]
Does github provide the automatic testing in pipelines? Gitlab provides.

**Comment by mbarbry** [comment]
I don't think such services are provided for free. But it would be very useful for sure!

**Comment by mbarbry** [comment]
The main PySCF repository uses Travis to perform unitests

https://travis-ci.org/github/pyscf/pyscf/builds/677198793

**Comment by kovalp** [comment]
Interesting. Gitlab provides ci. There are also linux and windows runners
with 2000 min per month for free.

Other topic, almost unrelated.

In a long term, there will be no pyscf-nao module as we know it. We have to
'move out' from pyscf. I am dreaming about a separate package which would
be aware of other packages such as pyscf and sisl.

**Comment by mbarbry** [comment]
Yes gitlab has more features than github in general, I personally have a preference for gitlab.

It would be nice to have a separate package, we would be more independent. What are your plans regarding this transfer? Actually, the github account where PySCF-NAO is located belongs to CFM.

Also, I should let you know that my contribution to the code will probably reduce in the next months.
I'm in fact starting a new job on Monday, therefore I had to take all my left holidays from my previous position, allowing me to be pretty active during the last weeks. But with my new job and the baby to take care, I will probably have little time left.

I think we did some nice improvements these last months and that the code is now pretty efficient. I'm thinking to start some meaningful calculations. I'm curious to analyze the shift in the energy levels as you approach two molecules using GW. Do you think that the code is ready for such application?

**Pull request merged**
